function getRandomImage() {
    let randomImage = new Array();

    randomImage[0] = "images/genderqueer.jpg";  
    randomImage[1] = "images/thehateyougive.jpg";  
    randomImage[2] = "images/lawnboy.jpg";  
    randomImage[3] = "images/allboysarentblue.jpg";  
    randomImage[4] = "images/outofdarkness.jpg";  
    randomImage[5] = "images/truediary.jpg";  
    randomImage[6] = "images/meandearl.jpg";  
    randomImage[7] = "images/thebluesteye.jpg";  
    randomImage[8] = "images/bookisgay.jpg";  
    randomImage[9] = "images/beyondmagenta.jpg";  
    randomImage[10] = "images/maus.jpg";  
    randomImage[11] = "images/handmaidstale.jpg";  
    randomImage[12] = "images/tokillamockingbird.jpg";  
    randomImage[13] = "images/beloved.jpg";  
    randomImage[14] = "images/13reasonswhy.jpeg";  
    randomImage[15] = "images/kiterunner.jpg";  
    randomImage[16] = "images/lookingforalaska.jpg";  
    randomImage[17] = "images/glasscastle.jpg";  
    randomImage[18] = "images/harrypotter1.jpg";  
    randomImage[19] = "images/1984.jpg";  
    randomImage[20] = "images/hungergames.jpeg";  
    randomImage[21] = "images/451.jpeg";  
    randomImage[22] = "images/giver.jpeg";  
    randomImage[23] = "images/lordoftheflies.jpg";  
    randomImage[24] = "images/1619.jpeg";  
    randomImage[25] = "images/allamericanboys.jpeg";  
    randomImage[26] = "images/persepolis.jpeg";  
    randomImage[27] = "images/slaughterhouse5.jpg";  
    randomImage[28] = "images/garciagirls.jpeg";  
    randomImage[29] = "images/nativeson.jpg";  
    randomImage[30] = "images/theperksof.jpg";  
    randomImage[31] = "images/forever.jpg";  
    randomImage[32] = "images/prep.jpeg";  
    randomImage[33] = "images/twilight.jpeg";  
    randomImage[34] = "images/blackbirds.jpeg";  
    randomImage[35] = "images/olivesocean.jpeg";  
    randomImage[36] = "images/lovelybones.jpeg";  
    randomImage[37] = "images/prisonerofazkaban.jpg";  
    randomImage[38] = "images/oneflew.jpg";  
    randomImage[39] = "images/wrinkle.jpeg";  
    randomImage[40] = "images/flowers.jpg";  
    randomImage[41] = "images/animalfarm.jpeg";  
    randomImage[42] = "images/annefrank.jpeg";  
    randomImage[43] = "images/endersgame.jpg";  
    randomImage[44] = "images/goask.jpeg";  
    randomImage[45] = "images/fightclub.jpeg";  
    randomImage[46] = "images/thelottery.jpeg";  
    randomImage[47] = "images/george.jpg";  
    randomImage[48] = "images/stamped.jpg";  
    randomImage[49] = "images/speak.jpg";  
    randomImage[50] = "images/whatgirls.jpg";  
    randomImage[51] = "images/beartown.jpg";  
    randomImage[52] = "images/kafka.jpeg";  
    randomImage[53] = "images/l8r.jpeg";  
    randomImage[54] = "images/melissa.jpeg";  
    randomImage[55] = "images/dearmartin.jpeg";  
    randomImage[56] = "images/anger.jpeg";  
    randomImage[57] = "images/drama.jpg";  
    randomImage[58] = "images/ghostboys.jpg";  
    randomImage[59] = "images/whitebird.jpg";  
    randomImage[60] = "images/ants.jpg";  
    randomImage[61] = "images/king.jpeg";  
    randomImage[62] = "images/lastnight.jpeg";  
    randomImage[63] = "images/jungle.jpeg"; 
    randomImage[64] = "images/greatgatsby.jpeg";
    randomImage[65] = "images/ring.jpg";

    //generate a number and provide to the image to generate randomly  
let number = Math.floor(Math.random()*randomImage.length);  

//return the images generated by a random number  
return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';  
    
}

